/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package homeautomation.swig;

public class CppDht22DummyJNI {
  public final static native long new_Dht22Dummy(int jarg1);
  public final static native double Dht22Dummy_getTemperature(long jarg1, Dht22Dummy jarg1_);
  public final static native double Dht22Dummy_getHumidity(long jarg1, Dht22Dummy jarg1_);
  public final static native void delete_Dht22Dummy(long jarg1);
}
