/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package homeautomation.swig;

public class CppDht22JNI {
  public final static native long new_Dht22(int jarg1);
  public final static native void delete_Dht22(long jarg1);
  public final static native double Dht22_getTemperature(long jarg1, Dht22 jarg1_);
  public final static native double Dht22_getHumidity(long jarg1, Dht22 jarg1_);
}
