/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package homeautomation.swig;

public class Dht22Dummy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Dht22Dummy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Dht22Dummy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CppDht22DummyJNI.delete_Dht22Dummy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Dht22Dummy(int pinNumber) {
    this(CppDht22DummyJNI.new_Dht22Dummy(pinNumber), true);
  }

  public double getTemperature() {
    return CppDht22DummyJNI.Dht22Dummy_getTemperature(swigCPtr, this);
  }

  public double getHumidity() {
    return CppDht22DummyJNI.Dht22Dummy_getHumidity(swigCPtr, this);
  }

}
