/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package homeautomation.swig;

public class LinkTransmitterSwigJNI {
  public final static native long new_RfLinkTransmitter(int jarg1);
  public final static native void delete_RfLinkTransmitter(long jarg1);
  public final static native void RfLinkTransmitter_setState(long jarg1, RfLinkTransmitter jarg1_, String jarg2, int jarg3, boolean jarg4);
}
