/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package homeautomation.swig;

public class RfLinkTransmitter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RfLinkTransmitter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RfLinkTransmitter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkTransmitterSwigJNI.delete_RfLinkTransmitter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RfLinkTransmitter(int pinNumber) {
    this(LinkTransmitterSwigJNI.new_RfLinkTransmitter(pinNumber), true);
  }

  public void setState(String systemCode, int unitCode, boolean state) {
    LinkTransmitterSwigJNI.RfLinkTransmitter_setState(swigCPtr, this, systemCode, unitCode, state);
  }

}
