/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package homeautomation.swig;

public class RfLinkTransmitterDummy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RfLinkTransmitterDummy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RfLinkTransmitterDummy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LinkTransmitterDummySwingJNI.delete_RfLinkTransmitterDummy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RfLinkTransmitterDummy(int pinNumber) {
    this(LinkTransmitterDummySwingJNI.new_RfLinkTransmitterDummy(pinNumber), true);
  }

  public void setState(boolean state) {
    LinkTransmitterDummySwingJNI.RfLinkTransmitterDummy_setState(swigCPtr, this, state);
  }

}
